<?php

	namespace model\main;

	use PDO;
	use PDOStatement;

	class PDOExtendedStatement extends PDOStatement
	{
		private $connection;

		protected function __construct(PDO $connection)
		{
			$this->connection = $connection;
		}

		public function execute($input_parameters = NULL)
		{
			$this->connection->query_count_increment();
			return parent::execute($input_parameters); // TODO: Change the autogenerated stub
		}
	}