<?php

	namespace model\main;

	use PDOStatement;

	class PDOExtendedStatement extends PDOStatement
	{
		private $connection;

		protected function __construct(PDOExtended $connection)
		{
			$this->connection = $connection;
		}

		public function execute($input_parameters = NULL)
		{
			$this->connection->queryCountIncrement();
			return parent::execute($input_parameters); // TODO: Change the autogenerated stub
		}
	}