name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.traineratwot.site/Traineratwot/WebToolTemplate"
      env:
        GITLAB_HOSTNAME: "gitlab.traineratwot.site"
        GITLAB_USERNAME: "traineratwot"
        GITLAB_PASSWORD: ${{secrets.GITLAB_PASSWORD}}
        GITLAB_PROJECT_ID: "25"
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
